export { default as jsConfig } from './js.ts'
export { default as tsConfig } from './ts.ts'
export { default as jsxConfig } from './jsx.ts'
export { default as tsxConfig } from './tsx.ts'
export { default as vueConfig } from './vue.ts'
