export { default as jsConfig } from './js'
export { default as tsConfig } from './ts'
export { default as jsxConfig } from './jsx'
export { default as tsxConfig } from './tsx'
export { default as vueConfig } from './vue'
